version: "3.7"

services:

  elasticsearch:
    # image: ghcr.io/dotcms/elasticsearch:7.9.1
    image: opensearchproject/opensearch:1.3.6
    environment:
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - data
      - bootstrap.memory_lock=true
      - CLI_JAVA_OPTS="-Xms3g -Xmx3g"
    ports:
      - 9200:9200
      - 9600:9600