version: '3.5'

networks:
    http_net:
    db_net:
    es_net:

volumes:
    dbdata-test:
    esdata-test:
    esdata-test-3x:

services:
    elasticsearch-test:
        image: ${ES_IMAGE:-opensearchproject/opensearch:1.3.6}
        environment:
            - cluster.name=elastic-cluster
            - discovery.type=single-node
            - data
            - bootstrap.system_call_filter=false
            - bootstrap.memory_lock=true
            - http.cors.enabled=true
            - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
            - http.cors.allow-credentials=true
            - 'ES_JAVA_OPTS=-Xmx1G'
            - plugins.security.disabled=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - ${ES_HOST_PORT:-9207}:9200
        volumes:
            - esdata-test:/usr/share/elasticsearch/data
        networks:
            - es_net

    elasticsearch-test-3x:
        image: ${ES_IMAGE_3X:-opensearchproject/opensearch:3.0.0}
        environment:
            - cluster.name=opensearch-3x-cluster
            - node.name=opensearch-3x-node
            - discovery.type=single-node
            - bootstrap.system_call_filter=false
            - bootstrap.memory_lock=true
            - http.cors.enabled=true
            - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
            - http.cors.allow-credentials=true
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx1G
            - DISABLE_INSTALL_DEMO_CONFIG=true
            - DISABLE_SECURITY_PLUGIN=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - ${ES_HOST_PORT_3X:-9201}:9200
        volumes:
            - esdata-test-3x:/usr/share/opensearch/data
        networks:
            - es_net

    dejavu:
        image: appbaseio/dejavu:3.6.0
        container_name: dejavu
        ports:
            - '1358:1358'
        links:
            - elasticsearch-test
    db-test:
        image: ${PG_IMAGE:-pgvector/pgvector:pg18}
        command: postgres -c 'max_connections=400' -c 'shared_buffers=128MB'
        environment:
            'POSTGRES_USER': ${DB_USER:-postgres}
            'POSTGRES_PASSWORD': ${DB_PWD:-postgres}
            'POSTGRES_DB': ${DB_DB:-dotcms}
        volumes:
            - dbdata-test:/var/lib/postgresql
            - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
        networks:
            - db_net
        ports:
            - '${DB_HOST_PORT:-5437}:5432'
