version: '3.5'

networks:
    http_net:
    db_net:
    es_net:

volumes:
    cms-shared:
    dbdata:
    esdata:

services:
    elasticsearch:
        image: ${ES_IMAGE:-opensearchproject/opensearch:1.3.6}
        environment:
            - cluster.name=elastic-cluster
            - discovery.type=single-node
            - data
            - bootstrap.system_call_filter=false
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xmx1G'
            - plugins.security.disabled=true
        ports:
            - ${ES_HOST_PORT:-9200}:9200
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - es_net

    dotcms:
        image: ${DOTCMS_IMAGE:-dotcms/dotcms:latest}
        profiles: ['local-docker']
        environment:
            CMS_JAVA_OPTS: '-Xmx1g '
            LANG: 'C.UTF-8'
            TZ: 'UTC'
            DOT_ES_AUTH_BASIC_PASSWORD: ${DOT_DB_BASE_URL:-admin}
            DOT_INITIAL_ADMIN_PASSWORD: ${DOT_INITIAL_ADMIN_PASSWORD:-admin}

            DOT_DATASOURCE_PROVIDER_STRATEGY_CLASS: ${DOT_DATASOURCE_PROVIDER_STRATEGY_CLASS:-com.dotmarketing.db.SystemEnvDataSourceStrategy}
            DOT_DB_DRIVER: ${DOT_DB_DRIVER:-org.postgresql.Driver}
            DOT_DB_BASE_URL: ${DOT_DB_BASE_URL:-jdbc:postgresql://db/dotcms?autosave=conservative}
            DOT_DB_USERNAME: ${DOT_DB_USERNAME:-postgres}
            DOT_DB_PASSWORD: ${DOT_DB_PASSWORD:-postgres}
            DOT_ES_ENDPOINTS: ${DOT_ES_ENDPOINTS:-http://elasticsearch:9200}

            'CMS_HEAP_SIZE': '1g'

            # "CUSTOM_STARTER_URL": 'https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240719/starter-20240719.zip'
        depends_on:
            - elasticsearch
            - db
        volumes:
            - cms-shared:/data/shared
            #- [serverpath]/license.zip:/data/shared/assets/license.zip
        networks:
            - db_net
            - es_net
        ports:
            - ${DOTCMS_HTTP_PORT:-8080}:8081
            - ${DOTCMS_HTTPS_PORT:-8443}:8443

    db:
        image: ${PG_IMAGE:-pgvector/pgvector:pg18}
        command: postgres -c 'max_connections=400' -c 'shared_buffers=128MB'
        environment:
            'POSTGRES_USER': ${DB_USER:-postgres}
            'POSTGRES_PASSWORD': ${DB_PWD:-postgres}
            'POSTGRES_DB': ${DB_DB:-dotcms}
        volumes:
            - dbdata:/var/lib/postgresql/18/data
        networks:
            - db_net
        ports:
            - '${DB_HOST_PORT:-5432}:5432'
