name: Release workflow
on: [push, pull_request]

jobs:
  setup-cicd-job:
    name: setup dot-cicd
    runs-on: ubuntu-latest
    steps:
      - name: prepare dot-cicd
        run: |
          chmod +x .cicd/discover.sh
          .cicd/discover.sh
  build-job:
    name: build base images
    runs-on: ubuntu-latest
    needs: setup-cicd-job
    steps:
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build dotcms image
        run: |
          dotcicd/library/pipeline/github/core/buildBase.sh
        env:
          PROJECT_ID: cicd-246518
#      - name: Curl Test Image Build
#        run: |
#          export CURRENT_BRANCH=$(basename $GITHUB_REF)
#          docker build -t gcr.io/$PROJECT_ID/curl-tests-image:$GITHUB_RUN_NUMBER \
#            --build-arg BUILD_FROM=COMMIT \
#            --build-arg BUILD_ID=$CURRENT_BRANCH \
#            --build-arg BUILD_HASH=$GITHUB_SHA \
#            --build-arg LICENSE_KEY=${{ secrets.DOTCMS_LICENSE }} \
#            --build-arg FROM_IMAGE=gcr.io/$PROJECT_ID/integration-tests-image:$GITHUB_RUN_NUMBER \
#            ./docker/tests/curl/
#        env:
#          PROJECT_ID: cicd-246518
#      - name: Curl Tests Compose
#        run: |
#          docker-compose \
#            -f ./docker/tests/curl/travis-curl-service.yml \
#            -f ./docker/tests/shared/sidecar-service-compose.yml \
#            -f ./docker/tests/shared/$DB_TYPE-docker-compose.yml \
#            -f ./docker/tests/shared/open-distro-docker-compose.yml \
#            up \
#            --abort-on-container-exit
#        env:
#          PROJECT_ID: cicd-246518
#          IMAGE_BASE_NAME: gcr.io/cicd-246518/curl-tests-image:${{ github.run_number }}
#          DB_TYPE: postgres
#          EXPORT_REPORTS: true
#          PROVIDER_DB_USERNAME: postgres
#          PROVIDER_DB_PASSWORD: postgres
#          BUILD_ID: ${{ github.ref }}
#          BUILD_HASH: ${{ github.sha }}

